---
- hosts: all
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Copy config file
      template:
        src: /home/ec2-user/ansible-dev/apache.j2
        dest: /tmp/apache.conf
